config/routes.rb
Rails.application.routes.draw do
  resources :trees
  get 'home/index'

  get 'home/pricing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  # Defines the root path route ("/")
  root "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/tree.rb
class Tree < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
  
    belongs_to :user
  
    validates :name, presence: true, length: { minimum: 4 }
    validate :at_least_one_field_filled_and_valid_length
  
    private
  
    def at_least_one_field_filled_and_valid_length
      if x.blank? && instagram.blank? && youtube.blank?
        errors.add(:base, "At least one of x, instagram, or youtube must be present")
      end
  
      if x.present? && x.length <= 5
        errors.add(:x, "must be more than 5 characters")
      end
  
      if instagram.present? && instagram.length <= 5
        errors.add(:instagram, "must be more than 5 characters")
      end
  
      if youtube.present? && youtube.length <= 5
        errors.add(:youtube, "must be more than 5 characters")
      end
    end
  end
  

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  # GET /trees or /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1 or /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    if current_user.tree
      redirect_to current_user.tree, notice: 'You already have a tree.'
    else
      @tree = Tree.new
    end
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees or /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully created." }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to tree_url(@tree), notice: "Tree was successfully updated." }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy!

    respond_to do |format|
      format.html { redirect_to trees_url, notice: "Tree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.require(:tree).permit(:name, :x, :instagram, :youtube, :user_id, :style)
    end
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>
  <% if tree.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :youtube, style: "display: block" %>
    <%= form.text_field :youtube %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> 

app/views/trees/_tree.html.erb
<%= stylesheet_link_tag "tree" %>

<div id="<%= dom_id tree %>" class="tree_item">
  <p>
    <strong>Name:</strong>
    <%= tree.name %>
  </p>

  <p>
    <strong>X:</strong>
    <%= tree.x %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= tree.instagram %>
  </p>

  <p>
    <strong>Youtube:</strong>
    <%= tree.youtube %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tree.user_id %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= tree.style %>
  </p>

</div>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "< Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="trees">
  <h1>Trees</h1>

  <div id="trees">
    <% @trees.each do |tree| %>
      <%= render tree %>
      <p>
        <%= link_to "Show this tree", tree %>
      </p>
    <% end %>
  </div>

  <% if current_user %>
    <% unless current_user.tree.present? %>
      <div class="new_tree"><%= link_to "New tree", new_tree_path %></div>
    <% end %>
  <% end %>
</div>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "< Back to trees", trees_path %>
</div>

app/views/trees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tree %>
<div>
<%= link_to "< Back to trees", trees_path %>
<% if user_signed_in? %> 

  <% if current_user.id == @tree.user_id %> <!-- Verifica se o usuário atual é o proprietário da árvore -->

       | <%= link_to "Edit this tree", edit_tree_path(@tree) %>



      <div class="destroy">
        <%= button_to "Destroy this tree", @tree, method: :delete %>
      </div>
    </div>
  <% end %>
<% end %>