config/routes.rb
Rails.application.routes.draw do
  resources :trees
  get 'home/index'

  get 'home/pricing'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }



  # Defines the root path route ("/")
  root "home#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<div class="navbar">
    <div class="navbar-brand">
        <%= link_to root_path do %>
            <%= image_tag("keyboard_key_t.ico", style: "width: 40px;") %>
        <% end %>
    </div>

    <div class="navbar-links">
        <% if user_signed_in? %>
            <div><%= link_to "My account", edit_user_registration_path %></div>
            <div><%= link_to "Sign out", destroy_user_session_path %></div>
        <% end %>
        <% unless user_signed_in? %>
            <div><%= link_to "Sign in", new_user_session_path %></div>
            <div><%= link_to "Sign up", new_user_registration_path %></div>
            <div><%= link_to "Pricing", home_pricing_path %></div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewLink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>